name: Deploy Cloudflare Worker (white-boat-72cb)

on:
  schedule:
    - cron: "0 */6 * * *"   # 每 6 小时执行一次 (UTC 0点、6点、12点、18点)
  workflow_dispatch:        # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish Worker white-boat-72cb
        run: wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
