name: Deploy Worker

on:
  schedule:
    - cron: '0 */6 * * *'   # 每 6 小时触发
  workflow_dispatch:         # 支持手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd Vless_workers_pages   # 进入包含 wrangler.toml 和 _worker.js 的目录
          wrangler deploy
